name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Compile Java code
      run: javac -d bin src/*.java

    - name: Create JAR file
      run: jar cfm Minesweeper.jar MANIFEST.MF -C bin .

    - name: Upload JAR file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Minesweeper
        path: Minesweeper.jar
